Repository joke2k/django-environ, pull requests merged in 2018-06, with the labels that each got.

#171 Warn about ignored netloc component in SQLite URLs
  environ/environ.py
  environ/test.py
Labels: bug

#155 Document usage of multiple env files; Fixes #143
  README.rst
Labels: docs

#158 Support PostgreSQL unix domain socket paths
  environ/environ.py
  environ/test.py
Labels: enhancement
