Repository joke2k/django-environ, pull requests merged in 2021-09, with the labels that each got.

#316 v0.6.0
  .coveragerc
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/cs.yml
  .github/workflows/docs.yml
  .gitignore
  .readthedocs.yml
  .travis.yml
  AUTHORS.rst
  BACKERS.rst
  CHANGELOG.rst
  CONTRIBUTING.rst
  LICENSE.txt
  MANIFEST.in
  README.rst
  SECURITY.rst
  appveyor.yml
  docs/Makefile
  docs/_static/.gitkeep
  docs/backers.rst
  docs/changelog.rst
  docs/conf.py
  docs/contributing.rst
  docs/docutils.conf
  docs/getting-started.rst
  docs/index.rst
  docs/license.rst
  docs/make.bat
  docs/tips.rst
  docs/types.rst
  environ/__init__.py
  environ/compat.py
  environ/environ.py
  environ/test.py
  setup.cfg
  setup.py
  tests/__init__.py
  tests/asserts.py
  tests/conftest.py
  tests/fixtures.py
  tests/test_cache.py
  tests/test_db.py
  tests/test_email.py
  tests/test_env.py
  tests/test_env.txt
  tests/test_path.py
  tests/test_schema.py
  tests/test_search.py
  tox.ini
Labels: release

#319 Add tests for #118
  tests/fixtures.py
  tests/test_env.py
  tests/test_env.txt
Labels: tests

#321 Add Elasticsearch5 to search scheme
  CHANGELOG.rst
  docs/types.rst
  environ/environ.py
  tests/conftest.py
  tests/test_search.py
Labels: enhancement

#322 Add Elasticsearch7 to search scheme
  CHANGELOG.rst
  docs/types.rst
  environ/environ.py
  tests/fixtures.py
  tests/test_env.py
  tests/test_schema.py
  tests/test_search.py
Labels: enhancement

#323 Use default option in Env.bytes()
  CHANGELOG.rst
  environ/environ.py
  tests/test_env.py
Labels: bug, enhancement

#251 Stop raising UserWarning if .env file isn't found
  environ/environ.py
Labels: enhancement

#325 Safely evaluate a string containing an invalid Python literal
  CHANGELOG.rst
  environ/environ.py
  tests/test_cache.py
  tests/test_utils.py
Labels: bug

#242 added env variable to point to .env file
  environ/environ.py
  tests/test_env.py
Labels: enhancement

#327 v0.7.0
  .github/workflows/docs.yml
  AUTHORS.rst
  BACKERS.rst
  CHANGELOG.rst
  README.rst
  docs/conf.py
  docs/getting-started.rst
  docs/tips.rst
  docs/types.rst
  environ/__init__.py
  environ/environ.py
  setup.py
  tests/conftest.py
  tests/fixtures.py
  tests/test_cache.py
  tests/test_env.py
  tests/test_env.txt
  tests/test_schema.py
  tests/test_search.py
  tests/test_utils.py
  tox.ini
Labels: release

#328 Add docker-style file variable support (fixes #189)
  README.rst
  docs/tips.rst
  environ/environ.py
  environ/fileaware_mapping.py
  tests/test_fileaware.py
Labels: enhancement

#329 Option to override existing variables with read_env
  docs/tips.rst
  environ/environ.py
  tests/test_env.py
Labels: enhancement
