Repository joke2k/django-environ, pull requests merged in 2022-06, with the labels that each got.

#390 Update actions
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/cs.yml
  .github/workflows/docs.yml
Labels: github_actions, dependencies

#374 Update tips to work with Python3
  docs/tips.rst
Labels: documentation

#391 Deprecate Env.unicode
  AUTHORS.rst
  CHANGELOG.rst
  README.rst
  docs/Makefile
  docs/api.rst
  docs/conf.py
  docs/deprecations.rst
  docs/docutils.conf
  docs/getting-started.rst
  docs/index.rst
  docs/tips.rst
  environ/__init__.py
  environ/compat.py
  environ/environ.py
  environ/fileaware_mapping.py
  tests/test_env.py
Labels: tech-debt

#394 Release v0.9.0
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/cs.yml
  .github/workflows/docs.yml
  .readthedocs.yml
  AUTHORS.rst
  CHANGELOG.rst
  README.rst
  docs/Makefile
  docs/api.rst
  docs/conf.py
  docs/deprecations.rst
  docs/docutils.conf
  docs/faq.rst
  docs/getting-started.rst
  docs/index.rst
  docs/install.rst
  docs/quickstart.rst
  docs/tips.rst
  docs/types.rst
  environ/__init__.py
  environ/compat.py
  environ/environ.py
  environ/fileaware_mapping.py
  setup.py
  tests/fixtures.py
  tests/test_db.py
  tests/test_env.py
  tests/test_env.txt
  tests/test_path.py
  tests/test_search.py
  tests/test_utils.py
  tox.ini
Labels: release

#395 Removed deprecated Env.unicode()
  CHANGELOG.rst
  docs/deprecations.rst
  environ/environ.py
  tests/test_env.py
Labels: tech-debt

#397 Add core redis compat if django 4+
  environ/compat.py
  tests/test_cache.py
  tests/test_env.py
Labels: enhancement

#399 Remove `environ.register_schemes` calls
  .github/workflows/codeql.yml
  CHANGELOG.rst
  environ/environ.py
Labels: tech-debt

#400 Value of dict can now contain an equal sign
  CHANGELOG.rst
  environ/environ.py
  tests/fixtures.py
  tests/test_env.py
  tests/test_env.txt
Labels: enhancement

#401 Fix code style
  CHANGELOG.rst
  docs/conf.py
  environ/__init__.py
  environ/compat.py
  environ/environ.py
  environ/fileaware_mapping.py
  tox.ini
Labels: tech-debt
