Repository joke2k/django-environ, pull requests merged in 2023-03, with the labels that each got.

#441 Rework trigger workflows strategy
  .github/workflows/build.yml
  .github/workflows/change-pr-target.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/cs.yml
  .github/workflows/docs.yml
Labels: github_actions

#439 Delete duplicated include in docs/quickstart.rst
  docs/quickstart.rst
Labels: bug, documentation

#442 Adds encoding parameter to read_env with default value 'utf8'
  environ/environ.py
Labels: enhancement

#425 Formally add support for Django 4.1
  README.rst
  setup.py
  tox.ini
Labels: enhancement, good first issue

#443 Release v0.10.0
  .github/dependabot.yml
  .github/workflows/build.yml
  .github/workflows/change-pr-target.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/cs.yml
  .github/workflows/docs.yml
  CHANGELOG.rst
  CONTRIBUTING.rst
  README.rst
  docs/conf.py
  docs/deprecations.rst
  docs/faq.rst
  docs/install.rst
  docs/license.rst
  docs/quickstart.rst
  docs/tips.rst
  environ/__init__.py
  environ/compat.py
  environ/environ.py
  environ/fileaware_mapping.py
  setup.py
  tests/fixtures.py
  tests/test_cache.py
  tests/test_db.py
  tests/test_env.py
  tests/test_env.txt
  tests/test_fileaware.py
  tests/test_path.py
  tests/test_utils.py
  tox.ini
Labels: release

#446 Update SQL Server engine as mssql-django
  CHANGELOG.rst
  environ/environ.py
  tests/test_db.py
Labels: enhancement, good first issue

#450 Prioritize django-redis for REDIS_DRIVER
  .gitignore
  environ/compat.py
Labels: bug

#456 Add support for Django 4.2
  README.rst
  setup.py
  tox.ini
Labels: enhancement
